### ISSUE TITLE
排序规则有点疑问

### ISSUE THREAD

**Issue by toddlerya** [zhongbaoyan/zhongbaoyan.github.io#1]
同样是全优成绩的，耐撞维修这几项看起来不是影响排名的主要因素，是按照前几项安全测试的成绩加权计算后排名的吗？
![image](https://user-images.githubusercontent.com/5418150/75693035-60398200-5ce1-11ea-888b-23242a1e415a.png)

**Comment by toddlerya** [comment]
看了下代码，大概知道怎么回事了，兄嘚数据都写到index.html里面了，也是辛苦了，打赏支持一下。

**Comment by zhongbaoyan** [comment]
感谢支持，之前的排序规则有点不明确。现在重新按照以下规则排了一下：

按照车内成员安全（包括正面25%、侧面、车顶、座椅头枕4个子项）G>A>M>P初步排行。
成绩相同的根据以下规则依次对比，直至分出排名先后：

1. 正面25%偏置碰撞总分
2. 侧面碰撞总分
3. 车顶强度载荷质量比
4. 座椅头枕总分
6. 正面25%偏置“假人伤害”分数；
5. 侧面碰撞结构完整性（B柱与座椅中线之间的距离）
7. 车顶强度峰值载荷
8. 辅助安全总分
9. 维修耐撞总分

* 若车内成员安全4项目包含P（较差）则排在所有车内成员安全无P车型之后
